export default {
    FETCH_HOTELS: 'FETCH_HOTELS',
    FETCH_HOTELS_WITH_COUNTRY: 'FETCH_HOTELS_WITH_COUNTRY',
    FETCH_HOTEL_DETAIL: 'FETCH_HOTEL_DETAIL',
    FETCH_SUGGEST: 'FETCH_SUGGEST',
    FETCH_DEFAULT_SUGGEST: 'FETCH_DEFAULT_SUGGEST',
    SET_TO_DEFAULT_SUGGEST: 'SET_TO_DEFAULT_SUGGEST',
    FETCH_HOST_INFOS: 'FETCH_HOST_INFOS',
};